### ISSUE TITLE
Make Undead spawns more resilient to your troll allies in S8, Lost

### ISSUE THREAD

**Issue by Ashmyr** [cooljeanius/The_Earths_Gut#16]
This is only a maybe but the scenario felt REALLY underwhelming. A leader who recruits a few units per turns or more frequent spawns could add more substance to the final half of the scenario.

**Comment by cooljeanius** [comment]
which difficulty?

**Comment by Ashmyr** [comment]
> which difficulty?

Easy.

**Comment by Ashmyr** [comment]
closing since you said you won't fix easy

**Comment by cooljeanius** [comment]
Actually I think I will actually address this one, since you have troll allies... my principle of "EASY difficulty can never be *too* easy" only applies to difficulty for the player, not the difficulty for your allied AI sides... I'm not going to increase the frequency of spawns, though, but rather I'm going to add events that make it easier for the undead to resist your troll allies.

**Comment by cooljeanius** [comment]
So, question: which in your opinion is a better way of checking if a side has no units left?
```
[if]
    [not]
        [have_unit]
            side=4
        [/have_unit]
    [/not]
```
or
```
[if]
    [have_unit]
        side=4
        count=0
    [/have_unit]
```
?
(cc @knyghtmare)

**Comment by cooljeanius** [comment]
I'm going to put this off for awhile...

**Comment by cooljeanius** [comment]
> I'm going to put this off for awhile...

Actually never mind...

> So, question: which in your opinion is a better way of checking if a side has no units left?
> 
> ```
> [if]
>     [not]
>         [have_unit]
>             side=4
>         [/have_unit]
>     [/not]
> ```
> 
> or
> 
> ```
> [if]
>     [have_unit]
>         side=4
>         count=0
>     [/have_unit]
> ```
> 
> ?

Update: I ended up going with the former in 9ee1831
