### ISSUE TITLE
S20 - A Cry for help, text suggestions

### ISSUE THREAD

**Issue by Konrad22** [cooljeanius/The_Earths_Gut#45]
find out the fate of -> find out about the fate of / investigate about the fate of
It is fine. -> That is acceptable.
into the battle -> to battle

Objectives
and then move them -> and they'll be moved to
^ actually, maybe change the way it is handled to match the text. As it is, there is no way to undo a choice without reloading the turn.
If possible, add a counter so the player knows how many units are already in the group. Maybe don't make the units disappear, but move them outside of the castle, and just change their side for now.

Also, map wise, I think it would be better if some damage was still visible, like way more damage. Story wise, they arrived here, went immediatly to the prison, and have been back for what, 2 days? And since then they fixed everything up?

**Comment by cooljeanius** [comment]
Text part kinda falls under #7, but I'll leave this separate anyways

**Comment by cooljeanius** [comment]
Fixed by [b9aace3](https://github.com/cooljeanius/The_Earths_Gut/commit/b9aace3d9271fcb2dd5a90ff92ef0b30c74ed405); I decided not to make any of the terrain changes because after looking at the maskfile used in S18, it actually didn't change the main hall that much, and I didn't want to make it any more damaged here than it was previously.

**Comment by Konrad22** [comment]
![grafik](https://user-images.githubusercontent.com/39015360/218718394-d748f0ed-73ce-4ead-8e53-28c54c85f4d8.png)
vs
![grafik](https://user-images.githubusercontent.com/39015360/218718577-c40ecbca-4dd2-4538-80a1-6b6e47814974.png)
